// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDqXenoB13f-XytCua2U-JByjRGrx5iDo',
    appId: '1:1030334470679:web:3eb12816f0e3a00a9dda52',
    messagingSenderId: '1030334470679',
    projectId: 'bukulapak-71871',
    authDomain: 'bukulapak-71871.firebaseapp.com',
    storageBucket: 'bukulapak-71871.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDyK8XURRqetH8qsSvo1JzP1L8xqQbbC0',
    appId: '1:1030334470679:android:38ac526c521046379dda52',
    messagingSenderId: '1030334470679',
    projectId: 'bukulapak-71871',
    storageBucket: 'bukulapak-71871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAchq-ojhgrngP7v7zl8EM6fKWD_DoYvxM',
    appId: '1:1030334470679:ios:6f30c7911756c5409dda52',
    messagingSenderId: '1030334470679',
    projectId: 'bukulapak-71871',
    storageBucket: 'bukulapak-71871.firebasestorage.app',
    iosBundleId: 'com.example.bukulapak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAchq-ojhgrngP7v7zl8EM6fKWD_DoYvxM',
    appId: '1:1030334470679:ios:6f30c7911756c5409dda52',
    messagingSenderId: '1030334470679',
    projectId: 'bukulapak-71871',
    storageBucket: 'bukulapak-71871.firebasestorage.app',
    iosBundleId: 'com.example.bukulapak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDqXenoB13f-XytCua2U-JByjRGrx5iDo',
    appId: '1:1030334470679:web:10ee8c018feaf9c99dda52',
    messagingSenderId: '1030334470679',
    projectId: 'bukulapak-71871',
    authDomain: 'bukulapak-71871.firebaseapp.com',
    storageBucket: 'bukulapak-71871.firebasestorage.app',
  );
}
